title: the Simplex theme
logo_img: /assets/img/icons/Title_Icon.jpg
favicon: /assets/favicon.ico
description: |
  안녕하세요, 문재현입니다.  
  이 블로그는 저의 성장과 기록을 남기기 위해 시작했습니다.

  앞으로 개발, 일상, 공부, 습관 관리 등 다양한 주제로 글을 올릴 예정입니다.  
  저와 비슷한 고민을 가진 분들께 도움이 되었으면 좋겠습니다.

  방문해주셔서 감사합니다.  
  댓글이나 피드백은 언제든 환영합니다!

global_tags: jekyll theme simplex golasblog responsive html5
copyright: © Golasowski 2021

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

lang : ko-KR

avatar : /assets/img/icons/Title_icon.png

timezone : Asia/Seoul

title : 난1렙이요의 블로그

tagline : 여러저러 하는 블로그

url : https://davidpro08.github.io

github_username : davidpro08
github_repo : davidpro08.github.io
github_url : https://github.com/davidpro08

author : 문재현
author_email : davidmoon0817@gmail.com
author_github : https://github.com/davidpro08

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Giscus comments
giscus:
  repo: davidpro08/davidpro08.github.io
  repo_id: R_kgDOMe0I5Q
  category: Comments
  category_id: DIC_kwDOMe0I5c4Cgl5Y
  mapping: pathname
  lang: ko

category_map:
  일기:
    title: "일기"
    color: "#ffcc00"
  지식:
    title: "지식"
    color: "#00bfff"
  프로젝트:
    title: "프로젝트"
    color: "#ff99cc"
  CS:
    title: "CS"
    color: "#aaff99"
  학교 공부 정리:
    title: "학교 공부 정리"
    color: "#ffccff"
  일상:
    title: "일상"
    color: "#cccccc"
  습관 잡기:
    title: "습관 잡기"
    color: "#ff9966"





